name: CI
on:
  push:
    branches:
      master
  pull_request:

jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run go vet
        run: |
          go vet ./...

      - name: Build code
        run: |
          make build

      - name: Run code
        run: |
          ./go-mailin8 | grep "Usage: go-mailin8 <address>"
