name: CI
on:
  push:
    branches:
      main
  pull_request:

jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run go vet
        run: |
          go vet ./...

      - name: Build code
        run: |
          make build-linux

      - name: Run code
        run: |
          ./go-mailin8_linux_amd64 | grep "Usage: go-mailin8_linux_amd64 <address>"
